# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91398896e9828316d5d0a18f1cc298c300e4f7e6bdb47b4f8860405360ea2662e101908ad4e4007ad9549619668a5d6e408060525dd5512ec42a74986907fe6

test:
  secret_key_base: ff099d697b045fa7d4c7341679762f646077849029d4e8e3077eeb76a0d71939096ad82001f91d48c84321807ecfe42e1e96d71bd4574ade81ce85730838fbc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
